import sys
sys.path.insert(0, './cardArchive/')


from deck import Deck
from cardsSimple import *

deck1 = Deck([Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Maiden(),
              Goblin(), 
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Mercenary(),
              Mercenary(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath()])
