from deck import Deck
from cardArchive import Fighter
from cardArchive import Goblin, Mercenary, Goliath, DeathDragon, Mercenary

deck2 = Deck([Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Mercenary(),
              Mercenary(),
              Mercenary(),
              Mercenary(),
              Mercenary(),
              Mercenary(),
              Mercenary(),
              Mercenary(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath()])
