from deck import Deck
from cardArchive import Fighter
from cardArchive import Goblin


deck2 = Deck([Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Goblin(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(),
              Fighter(),
              Fighter(),
              Fighter(),
              Fighter()])
