from deck import Deck
from cardArchive import *

deck1 = Deck([Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Fighter(), 
              Maiden(),
              Goblin(), 
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Maiden(),
              Mercenary(),
              Mercenary(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              DeathDragon(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath(),
              Goliath()])
